CREATE TABLE cars (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL);

CREATE TABLE external_defects (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	car_id INTEGER NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
	name TEXT);

CREATE TABLE external_defect_photos (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	external_defect_id INTEGER NOT NULL REFERENCES external_defects(id) ON DELETE CASCADE,
	photo BLOB,
	description TEXT);

CREATE TABLE tires (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	car_id INTEGER NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
	tire_side INTEGER NOT NULL);

CREATE TABLE tire_photos (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	tire_id INTEGER NOT NULL REFERENCES tires(id) ON DELETE CASCADE,
	photo BLOB,
	description TEXT);
